version: '3.7'

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
      tags:
        - "client:latest"
    environment:
      - API_ENDPOINT= http://server:3001
    ports:
      - 3000:3000
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
      tags:
        - "server:latest"
    ports:
      - 3001:3001
